### ISSUE TITLE
Fails to build: min_type_alias_impl_trait was removed

### ISSUE THREAD

**Issue by BenWiederhake** [thomvil/permutation-generator-rs#1]
Hi, apparently the min_type_alias_impl_trait nightly feature got removed:

```console
$ cargo build # In a private project
   Compiling bit-index v0.2.0
   Compiling permutation-generator v0.1.1
error[E0557]: feature has been removed
 --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/permutation-generator-0.1.1/src/lib.rs:1:12
  |
1 | #![feature(min_type_alias_impl_trait)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of full type_alias_impl_trait
```

**Comment by thomvil** [comment]
thanks for the heads up, i will look into this

**Comment by rljacobson** [comment]
The fix is super easy: just change `#![feature(min_type_alias_impl_trait)]` to `#![feature(type_alias_impl_trait)]`. 

It'd be super cool if you could publish an update so I can get rid of my custom fork—but I understand that life can get in the way. 

Thanks for sharing your code!

**Comment by thomvil** [comment]
I am so embarrassed that i took me this long this apply this trivial fix. I apologize.

All the best for the new year!
